module.exports = {
  // This "hack" ensures your IDE detects all normal Tailwind classes, while JIT is used when compiling the project.
  // All the normal Tailwind classes should show up in code completion. It can't show all the new classes generated by JIT.
  mode: process.env.NODE_ENV && 'jit',
  darkMode: false, // or 'media' or 'class'
  purge: [
    './components/**/*.ts',
    './components/**/*.tsx',
    './pages/**/*.tsx',
    './utilities/**/*.ts',
    './utilities/**/*.tsx',
  ],
  theme: {
    extend: {
      fontFamily: {
        "sans": "'PT Sans', 'Noto Sans TC', sans-serif",
        "serif": "'Noto Serif TC', serif",
        "mono": "'JetBrains Mono', Menlo, monospace",
      },
    },
  },
  variants: {
    extend: {
    },
  },
  plugins: [],
}
